name: Test CI

on:
  push:
    branches-ignore:
      - master
  pull_request:

env:
  PLATFORM: linux/amd64
  DOCKER_REPO: renovate/go
  DOCKER_TAGS: 1.14

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1

      - uses: actions/checkout@v2

      - name: docker cache 
        id: docker-cache
        uses: actions/cache@v1
        with:
          path: .cache
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build the Docker image
        run: |
          cache_from=$([ -d .cache ] && echo -n '--cache-from=type=local,src=.cache' || echo -n '')
          docker buildx build \
            --load \
            --tag ${DOCKER_REPO} \
            --cache-to=type=local,dest=.cache,mode=max \
            $cache_from \
            .

      - name: Test the Docker image
        run: ./run-tests.sh

      - name: Image history latest
        run: docker history ${DOCKER_REPO}

      - name: Images size
        run: docker image ls | grep ${DOCKER_REPO}

      - name: Publish (dry-run)
        uses: renovatebot/gh-action@v0
        with:
          command: "publish-docker"
          image: ${{ env.DOCKER_REPO }}
          tags: latest;${{ env.DOCKER_TAGS }}
          dry-run: true
